name: Slack post

inputs:
  text:
    required: true
    type: string
  color-code:
    required: true
    type: string
  thread_ts:
    required: false
    type: string
  reply_broadcast:
    required: false
    type: boolean
    default: false

outputs:
  ts: # timestamp of message posted
    description: 'The timestamp on the message that was posted into Slack when using bot token'
    value: ${{ steps.slack-post.outputs.ts }}

runs:
  using: "composite"
  steps:
    - name: Slack post
      id: slack-post
      run: |
        echo 'color: ${{ inputs.color-code }}
        ${{ inputs.text }}' >> $GITHUB_STEP_SUMMARY

        echo 'ts=dummy-ts' >> $GITHUB_OUTPUT
      shell: bash
