name: Slack post

inputs:
  text:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Slack post
      run: |
        echo '
        <div style="color: #FF5722;">
        ${{ inputs.text }}
        </div>' >> $GITHUB_STEP_SUMMARY
      shell: bash
