name: Slack post

inputs:
  text:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Slack post
      run: |
        echo '${{ inputs.text }}' >> $GITHUB_STEP_SUMMARY
      shell: bash
