name: Slack post workflow end

runs:
  using: "composite"
  steps:
    - name: Set parameters
      id: set-parameters
      run: |
        echo '${{ toJSON(job) }}'
        gh run view '${{ github.run_id }}' --json jobs | jq -r '[.jobs[].conclusion | select(. != "")]'
        sleep 3
        step_conclusions=$(
          gh run view '${{ github.run_id }}' --json jobs \
            | jq -c '[.jobs[].steps[].conclusion]'
        )
        echo "step_conclusions: ${step_conclusions}"

        if [[ "${step_conclusions}" =~ 'failure' ]]; then
          echo 'result-message=失敗しました' >> $GITHUB_OUTPUT
          echo 'color-code=red' >> $GITHUB_OUTPUT
        elif [[ "${step_conclusions}" =~ 'canceled' ]]; then
          echo 'result-message=キャンセルされました' >> $GITHUB_OUTPUT
          echo 'color-code=gray' >> $GITHUB_OUTPUT
        else
          echo 'result-message=成功しました' >> $GITHUB_OUTPUT
          echo 'color-code=green' >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash

    - name: Slack post
      uses: ./.github/actions/slack-post
      with:
        text: '[${{ github.event.inputs.env }}] ${{ github.workflow }} が${{ steps.set-parameters.outputs.result-message }}'
        color-code: '${{ steps.set-parameters.outputs.color-code }}'
