name: Slack post workflow end

runs:
  using: "composite"
  steps:
    - name: Slack post
      id: slack-post
      uses: ./.github/actions/slack-post
      with:
        text: '[${{ github.event.inputs.env }}] ${{ github.workflow }} が成功しました'
        color-code: green
