name: Slack post workflow end

inputs:
  success:
    required: true
    type: boolean
  failure:
    required: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Set success environment variables
      # if: inputs.success == 'true'
      run: |
        echo '${{ toJSON(github) }}'
        echo 'RESULT_MESSAGE=成功しました' >> $GITHUB_ENV
        echo 'COLOR_CODE=green' >> $GITHUB_ENV
      shell: bash

    - name: Set failure environment variables
      if: inputs.failure == 'true'
      run: |
        echo 'RESULT_MESSAGE=失敗しました' >> $GITHUB_ENV
        echo 'COLOR_CODE=red' >> $GITHUB_ENV
      shell: bash

    - name: Slack post
      uses: ./.github/actions/slack-post
      with:
        text: '[${{ github.event.inputs.env }}] ${{ github.workflow }} が${{ env.RESULT_MESSAGE }}'
        color-code: '${{ env.COLOR_CODE }}'
