name: Slack post workflow start

runs:
  using: "composite"
  steps:
    - name: Slack post
      uses: ./.github/actions/slack-post
      with:
        text: '[${{ github.event.inputs.env }}] ${{ github.workflow }} を開始しました'
