name: Multiple jobs

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: string
        default: staging
      sleep-seconds:
        required: true
        type: string
        default: '1'

jobs:
  slack-post-workflow-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Slack post workflow start
        uses: ./.github/actions/slack-post-workflow-start

