name: Single job

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: string
        default: staging
      sleep-seconds:
        required: true
        type: string
        default: '1'

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Slack post workflow start
        uses: ./.github/actions/slack-post-workflow-start

      - name: Dummy step
        run: sleep '${{ inputs.sleep-seconds }}'

      - name: Slack post workflow end
        uses: ./.github/actions/slack-post-workflow-end
